package generate

var GoTemplate = `// Code generated by autohttp. DO NOT EDIT.

package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Println("Session ID:", {{printf "%q" .SessionID}})
	fmt.Println("Target URL:", {{printf "%q" .TargetURL}})
	fmt.Printf("Exchange count: %d\n", {{.ExchangeCount}})
	fmt.Println()
	fmt.Println("Dependencies:")
{{- if .Dependencies }}
{{- range .Dependencies }}
	fmt.Printf("  %s -> %s: %s\n", {{printf "%q" .From}}, {{printf "%q" .To}}, {{printf "%q" .Value}})
{{- end }}
{{- else }}
	fmt.Println("  (none)")
{{- end }}
	os.Exit(0)
}
`
